### ISSUE TITLE
Duplicate code in evm and starky crate?

### ISSUE THREAD

**Issue by vivekvpandya** [0xPolygonZero/plonky2#1098]
It seems there are lots of duplicated code between evm and starky crate, like constraint_consumer.rs, vanishing_polynomials.rs, get_challanges.rs and so on. 

Also it seems cross_table_lookup is also generic so it can also be put under starky crate.

Any specific reason why above is not done yet?

**Comment by Nashtare** [comment]
Hi! There was indeed a lot of code duplication, initially because we needed additional features that `starky` didn't have and that seemed too specific to the `evm` crate.
We're proceeding to a major code migration to update `starky` and leveraging it within the `plonky2_evm` crate. The remaining associated PR is this one: #1503, that should be resolving this issue.
