### ISSUE TITLE
Add missing constraints

### ISSUE THREAD

**Issue by nbgl** [0xPolygonZero/plonky2#1150]
Operations that still have some missing constraints:

- [x] `KECCAK_GENERAL`: [Memory channels not constrained.](https://github.com/mir-protocol/plonky2/blob/bfd6b98884fe59472841f89ad51cc3e5f4c02b3e/evm/src/cpu/stack.rs#L73)
- [x] `PROVER_INPUT`: Totally unconstrained. [Need to constrain the memory channels](https://github.com/mir-protocol/plonky2/blob/bfd6b98884fe59472841f89ad51cc3e5f4c02b3e/evm/src/cpu/stack.rs#L74) (disabling unused ones) and range-check all the limbs to 32 bits.
- [x] `SHL`/`SHR`: [Missing CTL to the arithmetic table.](https://github.com/mir-protocol/plonky2/blob/bfd6b98884fe59472841f89ad51cc3e5f4c02b3e/evm/src/cpu/cpu_stark.rs#L83)
- [ ] `PUSH1`-`PUSH32`: Unconstrained. (assigned to @Nashtare)
- [x] Syscalls/exceptions: [`output[6]` needs to be range-checked to 32 bits.](https://github.com/mir-protocol/plonky2/blob/b3f00d4ab828354955ed4f31bd2ec8057cdd5bf3/evm/src/cpu/syscalls_exceptions.rs#L112)

In addition, [the memory CTL is currently disabled](https://github.com/mir-protocol/plonky2/blob/bfd6b98884fe59472841f89ad51cc3e5f4c02b3e/evm/src/all_stark.rs#L108).

**Comment by Nashtare** [comment]
By the way, for the memory CTL, there is an attempt at re-enabling it in #1026 which has been pending for quite a bit now!
I think @LindaGuiga had also asked for the range-checks whether these should be over 32 bits or a different range.

**Comment by nbgl** [comment]
Yes, the syscall/exception range checks should be 32 bits. I've updated this issue to specify :) (cc @LindaGuiga)

**Comment by LindaGuiga** [comment]
I will start dealing with the constraints related to syscalls and prover_input!

**Comment by Nashtare** [comment]
@nbgl I can take care of the other two items if they aren't taken on your side!

**Comment by LindaGuiga** [comment]
@nbgl For the syscall/exception range checks, I was thinking of separating `output[6]` into two 16-bit limbs, doing a range check on the two limbs, and adding a constraint to check that the two limbs add up to the original value. Following what is done in `ArithmeticStark`, this leads to 7 new columns in the cpu:
- Two for the two limbs to range check
- Two for the permuted limbs
- Two for the permuted tables
- One for the lookup table
Does this sound good or did you have something else in mind?

**Comment by LindaGuiga** [comment]
@nbgl  For the range checks of `PROVER_INPUT`, the syscalls and exceptions, we have a branch that should work[ here](https://github.com/topos-protocol/plonky2/tree/cpu-range-checks). But it adds 49 columns to `CpuStark`, as it follows the example of `ArithmeticStark` for the range checks and each 32-bit limb is split into two 16-bit limbs. Thus, it requires 6 * n + 1 columns where n is the number of 32-bit limbs to check (n=8 in our case, since we want to check all `PROVER_INPUT` limbs). 

Another approach we thought of to avoid adding columns to `CpuStark` would be to add a row for each `PROVER_INPUT`, syscall or exception operation in the `ArithmeticStark`. This is not implemented yet, but I think it also requires additional columns in `ArithmeticStark` to store the 32-bit values though, as well as 2 additional `looking_tables` in `ctl_arithmetic()`.

What do you think of these approaches, and did you have something else in mind for the range checks in the cpu?

**Comment by nbgl** [comment]
49 extra columns is a _lot_. I'd much rather do it through `ArithmeticStark`, as you described.

We wouldn't need to store 32-bit values in the arithmetic table though—the existing 16-bit columns are fine. Note that every output of the arithmetic table is range checked to 16-bit limbs, so you can just combine two of them to make a 32-bit limb :)

Does my explanation make sense? I'm happy to jump on a call if that'd be easier!

**Comment by LindaGuiga** [comment]
The explanation makes sense, thanks a lot!
