### ISSUE TITLE
How to use assert_one() in builder?

### ISSUE THREAD

**Issue by tikhono** [0xPolygonZero/plonky2#871]
I could not find any documentation in that regard. Maybe add small example of that function usage or, at least, description in docs?

**Comment by Nashtare** [comment]
`assert_zero` and `assert_one` are in essence similar to `connect`, when we want to add a copy constraint between two `Target`s of a circuit, except that those connect to a constant (respectively 0 and 1).

For instance the Fibonacci example currently allows someone to provide the two starting integers of the sequence. You could enforce the inputs to be 0 and 1, or 1 and 1, depending on your definition of Fibonacci, so that a prover cannot arbitrarily decide how they want to start the sequence.
